name: python_building CI
env:
  DOWNLOAD_FOLDER_NAME : "Temping-downloads"
  INSTALL_FOLDER_NAME  : ""
  PYTHON_VERSION       : "3.7.3"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  building:

    runs-on: ubuntu-latest

    steps:
    - name: Installing necessary packages
      run: sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev tar

    - name: Make download folder
      run: |
         cd ~
         mkdir "./${{ env.DOWNLOAD_FOLDER_NAME }}"
         cd "./${{ env.DOWNLOAD_FOLDER_NAME }}"

    - name: Download python source archive
      run: wget --no-check-certificate "https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz"

    - name: Unpack python sources
      run: tar xvf Python-${{ env.PYTHON_VERSION }}.tgz -C .

    - name: Construct path to installation folder
      run: | 
         echo "The environment variable INITIAL_FOLDER_NAME is ${{ env.INSTALL_FOLDER_NAME }}."
         cd ~
         INSTALL_FOLDER_NAME=$(pwd)/.python-${DOWNLOADING_PYTHON_VERSION}
         cd ./Python-${{ env.PYTHON_VERSION }}

    - name: Check path to installation folder
      run: echo "Now the environment variable INITIAL_FOLDER_NAME is ${{ env.INSTALL_FOLDER_NAME }}."

    - name:  Configuring for building
      run: ./configure --enable-optimizations --prefix=${{ env.INSTALL_FOLDER_NAME }}

#
#    - name: Install dependencies
#      run: make
#
#    - name: Run check
#      run: make check
#
#    - name: Run distcheck
#      run: make distcheck

#  building_script_run:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Clone repository
#    - uses: actions/checkout@v3
#
#    - name: Python building script running
#      run: ./configure

